config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  root 'homepage#index'

  get 'homepage/index'

  get 'homepage/about_me'

  get 'homepage/contact_me'

  get 'homepage/ajax2'

  get 'blog_posts/index'

  get 'blog_comments/index'

  get 'blogs/index'

  get 'homepage/marta'

  resources :blog_comments

  resources :blog_posts

  resources :blogs

  resources :homepage

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	
  has_many :blog_posts
end

app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base
	belongs_to :blog_post
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	has_many :blog_comments
	belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController
  before_action :set_blog_comment, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /blog_comments
  # GET /blog_comments.json
  def index
    @blog_comments = BlogComment.all
  end

  # GET /blog_comments/1
  # GET /blog_comments/1.json
  def show
  end

  # GET /blog_comments/new
  def new
    @blog_comment = BlogComment.new
  end

  # GET /blog_comments/1/edit
  def edit
  end

  # POST /blog_comments
  # POST /blog_comments.json
  def create
    @blog_comment = BlogComment.new(blog_comment_params)

    respond_to do |format|
      if @blog_comment.save
        format.html { redirect_to @blog_comment, notice: 'Blog comment was successfully created.' }
        format.json { render :show, status: :created, location: @blog_comment }
      else
        format.html { render :new }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_comments/1
  # PATCH/PUT /blog_comments/1.json
  def update
    respond_to do |format|
      if @blog_comment.update(blog_comment_params)
        format.html { redirect_to @blog_comment, notice: 'Blog comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_comment }
      else
        format.html { render :edit }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_comments/1
  # DELETE /blog_comments/1.json
  def destroy
    @blog_comment.destroy
    respond_to do |format|
      format.html { redirect_to blog_comments_url, notice: 'Blog comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_comment
      @blog_comment = BlogComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_comment_params
      params.require(:blog_comment).permit(:title, :post, :blogger_id)
    end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :post, :blogger_id)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog = Blog.create(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :avatar)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  	
  	require 'open-uri'
  	require 'json'



  def about_me
  end

  def contact_me
  end

  def ajax
  end

  def marta
  	@results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/blog_comments/_form.html.erb
<%= form_for(@blog_comment) do |f| %>
  <% if @blog_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_comment.errors.count, "error") %> prohibited this blog_comment from being saved:</h2>

      <ul>
      <% @blog_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post %>
  </div>
  <div class="field">
    <%= f.label :blogger_id %><br>
    <%= f.text_field :blogger_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_comments/edit.html.erb
<h1>Editing blog_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_comment %> |
<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/index.html.erb
<h1>Blog Comments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th>Blogger</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_comments.each do |blog_comment| %>
      <tr>
        <td><%= blog_comment.title %></td>
        <td><%= blog_comment.post %></td>
        <td><%= blog_comment.blogger_id %></td>
        <td><%= link_to 'Show', blog_comment %></td>
        <td><%= link_to 'Edit', edit_blog_comment_path(blog_comment) %></td>
        <td><%= link_to 'Destroy', blog_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Blog comment', new_blog_comment_path %>

app/views/blog_comments/new.html.erb
<h1>New blog_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog_comment.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @blog_comment.post %>
</p>

<p>
  <strong>Blogger:</strong>
  <%= @blog_comment.blogger_id %>
</p>

<%= link_to 'Edit', edit_blog_comment_path(@blog_comment) %> |
<%= link_to 'Back', blog_comments_path %>

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post %>
  </div>
  <div class="field">
    <%= f.label :blogger_id %><br>
    <%= f.number_field :blogger_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing blog_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<h1>Blog Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th>Blogger</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_posts.each do |blog_post| %>
      <tr>
        <td><%= blog_post.title %></td>
        <td><%= blog_post.post %></td>
        <td><%= blog_post.blogger_id %></td>
        <td><%= link_to 'Show', blog_post %></td>
        <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
        <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Blog post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<h1>New blog_post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog_post.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @blog_post.post %>
</p>

<p>
  <strong>Blogger:</strong>
  <%= @blog_post.blogger_id %>
</p>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= form_for @blog, :url => blogs_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>


<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= image_tag blog.avatar.url (:thumb)%></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= form_for @blog, :url => blogs_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>

<br>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<%= image_tag @blog.avatar.url(:thumb)%>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/homepage/about_me.html.erb
<div class="panel" >

<h2>About Me</h2>
</br> 
<p> My name is Kevin Nall and I am currently a student at Tech Talent South in their Intensive Coding Course for Ruby on Rails. Over the course of eight weeks, I have learned the following languages and concepts. <p>

<li>Ruby on Rails</li>
<li>HTML</li>
<li>CSS</li>
<li>Javascript</li>
<li>AJAX</li>
<li>Understanding API's</li>
<li>Domain Modeling</li>
<li>HTTP and RESTful Design</li>

app/views/homepage/ajax2.html.erb
<script type="text/javascript">
	function loadBlogPosts(){

	$.getJSON("/blog_posts.json", function(data){
		// console.log (data);

		var html = "";


		$.each(data, function (index){
		
			// alert(data[index].title);
			html += "<b>" + data[index].title + "</b><br>";

	});
			$("#blog_posts").html(html);

});


}


</script>

<div id="blog_posts" name="blog_posts">
	<a href="javascript:loadBlogPosts();">
	This is where blog posts go </a>
</div>

app/views/homepage/contact_me.html.erb
<div class="panel2" >

	<h2>Contact Me</h2>
	<br>
	<p>Please email me at kmnall@icloud.com with any questions.</p>
	<br>
	<p>Find me on Linkedin</p>
	<script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
	<script type="IN/MemberProfile" data-id="https://www.linkedin.com/pub/kevin-nall/8a/5a9/61a" data-format="hover"></script>

</div>

app/views/homepage/index.html.erb
<div class="panel">


<h2>Welcome to my Blog and Portfolio</h2>

<p> Bacon ipsum dolor sit amet pork bresaola venison ham hock, kielbasa sirloin shoulder ham chicken sausage pork loin doner rump meatloaf. Drumstick tongue prosciutto, tri-tip t-bone salami pastrami sausage corned beef. Salami frankfurter leberkas turducken, landjaeger prosciutto t-bone shankle pastrami pork belly tri-tip shank. Bresaola chuck sirloin pork loin. 
<br><br>
Pancetta salami jerky beef hamburger shankle t-bone chuck swine. Beef ribs capicola doner, ham hock prosciutto shank bacon pig leberkas drumstick. Biltong salami jowl bacon corned beef flank ham hamburger turkey meatloaf t-bone turducken. Landjaeger strip steak salami tail flank. Capicola bresaola ball tip t-bone. Chicken pork chop swine cow porchetta tongue boudin capicola beef ribs tri-tip frankfurter. Pork loin tail short loin meatball turducken sausage chicken ribeye tenderloin kielbasa flank meatloaf filet mignon.
</p>

app/views/homepage/marta.html.erb
There are <%=@results.count%> bus routes currently

<br><br>

<%@results.each do |result| %>
	latitude: <%= result['LATITUDE']%><br>
	longitude: <%= result['LONGITUDE']%><br>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Kevin Nall's Portfolio and Blog </title>

  <link rel="icon" 
        type="image/jpg" 
        href="http://stickurz.com/1350-thickbox_default/palm-tree.jpg">

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body class="mypage">


<nav class="navbar navbar-inverse" role="navigation">
  	 <a class="navbar-brand" href="/homepage/index">Home</a>
      <a class="navbar-brand" href="/homepage/about_me">About Me</a>
      <a class="navbar-brand" href="/homepage/contact_me">Contact Me</a>
      <a class="navbar-brand" href="/blogs/index">Blogs</a>
      <a class="navbar-brand" href="/blog_posts/index">Blog Posts</a>
      <a class="navbar-brand" href="/blog_comments/index">Blog Comment</a>

      <form class="navbar-form pull-right">
      
        <% if user_signed_in? %>

        <%= link_to "Sign out",destroy_user_session_path, method: :delete, class: "button" %>

        <% else %>

        <%= link_to "Sign in",new_user_session_path %>

        <%end%>
  
      </form>
</nav>
  
<%= yield %>

</body>
</html>